### ISSUE TITLE
Add ability to exit matlab-proxy when Matlab is inactive/idle

### ISSUE THREAD

**Issue by sfeltman** [mathworks/matlab-proxy#10]
I would like the ability to specify an inactive/idle timeout for mablab-proxy that would completely exit the app. This is useful when users have forgotten they started a server.

**Comment by prabhakk-mw** [comment]
@sfeltman ,

**Comment by prabhakk-mw** [comment]
Thank you @sfeltman 
The development teams have been notified of this feature request. 
I'll keep this issue open until we have a resolution!
