### ISSUE TITLE
Error when opening matlab-proxy

### ISSUE THREAD

**Issue by LockyChao** [mathworks/matlab-proxy#12]
Hello! I installed matlab-proxy in anaconda environment, Python3.9, Ubuntu 20.04.5. The installation seems fine, but when I type in  env MWI_BASE_URL="/matlab" matlab-proxy-app  I met error "Invalid input parameter: 'contextRoot'. " (shown in below figure), and the website stuck in "starting. This may take several minutes" for hours and not showing matlab at all.
<img width="733" alt="image" src="https://user-images.githubusercontent.com/42677174/219583983-a383e933-ba8c-4e5e-8a15-194ee4f0601c.png">

**Comment by diningPhilosopher64** [comment]
Hi @LockyChao ,

Thank you for trying out the `matlab-proxy` package. 

The oldest supported MATLAB version for `matlab-proxy` is `R2020b`. 
You can check all the requirements for `matlab-proxy` under the [requirements](https://github.com/mathworks/matlab-proxy#requirements) section.
