### ISSUE TITLE
WebGL support?

### ISSUE THREAD

**Issue by m2Giles** [mathworks/matlab-proxy#13]
Previously while running the MATLAB docker container I thought there was webgl support for plotting. While this was hit or miss between Firefox and Google Chrome (WebGL tests work with both), I've noticed that the docker container no longer has the starting with web graphics note.

Additionally, when using the matlab-proxy-app directly I've never seen WebGL work with rendererinfo and the fallback to software opengl.

Is webgl actually supported? Or do we always have software opengl when running matlab-proxy-app due to Xvfb?

**Comment by prabhakk-mw** [comment]
Yes, it does seem like the usage of Xvfb results in using the software opengl package.
