### ISSUE TITLE
Cannot pass authentication

### ISSUE THREAD

**Issue by belafdil-chakib** [mathworks/matlab-proxy#14]
OS: Debian buster
Matlab R2022b

After running ``` env MWI_BASE_URL="/matlab" matlab-proxy-app ``` and access the web page for authentication, nothing happens after entering my password.

Fyi, if I try a wrong password, it warns me that it is wrong.

I tried on Firefox and chrome everything allowed (cookies and pop-up)

Is it possible to authenticate differently ?

**Comment by prabhakk-mw** [comment]
@belafdil-chakib 

By authentication do you mean this screen:
![image](https://user-images.githubusercontent.com/64955767/234476441-c20e6383-87cd-4049-aa07-b58b683fb734.png)

If yes, then could you please share any logs from the terminal from which you launched `matlab-proxy-app`

We have sometimes seen this screen hang when licensing information returns values that suggest that a user is not licensed for the version of MATLAB that he is attempting to login to.

**Comment by prabhakk-mw** [comment]
@belafdil-chakib This issue is being closed. Please re-open the issue with the information requested, if you are still in need of assistance.
