### ISSUE TITLE
Add-On Explorer Not Found Error

### ISSUE THREAD

**Issue by nlvw** [mathworks/matlab-proxy#15]
Using the latest version of the proxy, at this time (0.5.8), the Add-On Explorer doesn't work and displays a "Not Found" error.  Running the same container, inside a XFCE desktop using the regular MATLAB GUI, the Add-On Explorer works without issue.

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/5723368/228081789-1a4feb0e-3088-4569-a390-7b32397bf4d1.png">

I was not able to find any errors in the logs.

**Comment by prabhakk-mw** [comment]
Hi @nlvw 

Unfortunately Add-On Explorer is currently unsupported when accessed through `matlab-proxy`. There is ongoing development to introduce support for this capability.

Using the VNC approach to access the Add-On manager is the recommended workaround at the moment.

We regret the inconvenience this may have caused to you!
Thank you for using `matlab-proxy`!
