### ISSUE TITLE
UI is not persistent when browser is refreshed

### ISSUE THREAD

**Issue by nlvw** [mathworks/matlab-proxy#16]
When the page is refreshed, or if a user closes the page and comes back later, the UI and command window are reset.  Any open panels, like Add-On Manager, will no longer be open.  Also, the command window will be blank and have no history.  Running commands/scripts will still be running but you lose all output history and the command window will not work until the previous process finishes.

To test this run the matlab proxy, in the command window run `pause(60); disp('sleep test')`, refresh the page, and wait 60 seconds.  You will see the output but not the history of actually running the command.

Ideally a user should be able to leave (close page), come back, and resume work where they left off without losing any work or progress.  We do this currently with a combination of XFCE, VNC, and the regular MATLAB GUI.  Hopefully the Proxy can allow for this use case.

Proxy = 0.5.8
Matlab = 2023a

**Comment by prabhakk-mw** [comment]
Hi @nlvw 

The concerned development teams have been notified of this feature request! I'll keep this issue open until we have a resolution.

Thank you for your valuable feedback!

**Comment by prabhakk-mw** [comment]
It is unlikely that this issue will be resolved anytime in the near future. 
Closing this for now, as there is little we can do about this from `matlab-proxy`.
