### ISSUE TITLE
Unable to interact with Matlab in browser

### ISSUE THREAD

**Issue by AndrewHerzing** [mathworks/matlab-proxy#23]
OS: Ubuntu 20.04.6
Matlab: R2021b
jupyterlab: 3.6.3
jupyter_server: 1.23.4
jupyter-matlab-proxy: 0.7.1
matlab-proxy: 0.7.7

I can successfully open Matlab in the browser from Jupyter. If I press enter, a new >>> terminal prompt is created. However, I I try to enter an actual command the program freezes and nothing ever happens again:

![image](https://github.com/mathworks/matlab-proxy/assets/15435952/cd60e334-cdbb-4237-bede-4c7cffa01ed6)

**Comment by prabhakk-mw** [comment]
Closing based on comment in https://github.com/mathworks/jupyter-matlab-proxy/issues/66
