### ISSUE TITLE
configure timeouts

### ISSUE THREAD

**Issue by jhgoebbert** [mathworks/matlab-proxy#24]
Hello everyone,

we came across timeout-issues lately in our setup which can be seen from a screenshot below.

It seems to me as if these issues are timeouts from the function `fetchWithTimeout()`:
It would be great we could increase these timeouts (perhaps by a factor one can set through an environment variable) for systems where certain steps can take longer that 10-15 seconds.

Best regards,
Jens 

P.S: I came across a very short timeout (`100`) which might be a bug - see below.

Timout-Screenshot:
![image](https://github.com/mathworks/matlab-proxy/assets/9266792/91310f39-efdd-4f2b-b6f7-923c8727230c)

fetchWithTimout():
https://github.com/search?q=repo%3Amathworks%2Fmatlab-proxy%20fetchWithTimeout&type=code
![image](https://github.com/mathworks/matlab-proxy/assets/9266792/260f4923-10a7-456b-a624-901b4ab74edc)

**Comment by prabhakk-mw** [comment]
Hi @jhgoebbert 


The highlighted value in the screenshot is from a test file that we use to test these components. 
It shouldn't effect production workflows. 

Can you confirm that MATLAB has indeed started up in the background?

Do you have any logs coming from matlab-proxy that you could share when this occurs? 

If IIRC, there is a 2 minute timeout where we wait for MATLAB to respond to the proxy. 

How long does MATLAB typically take to launch in this environment?

Is this issue sporadic?

**Comment by prabhakk-mw** [comment]
@jhgoebbert 
Please use the environment variable `MWI_PROCESS_START_TIMEOUT` to configure the timeout  in seconds that you would like to set for your users. If this value is unset, the default value is 120 seconds.

**Comment by jhgoebbert** [comment]
Great, thank you!

**Comment by jhgoebbert** [comment]
btw: I also increased the timeout of jupyter_matlab_proxy
https://github.com/mathworks/jupyter-matlab-proxy/blob/main/src/jupyter_matlab_proxy/__init__.py#L96
