### ISSUE TITLE
[Usage of MathWorks Online Licensing failed.License Manager Error 4410 ]

### ISSUE THREAD

**Issue by dutLQG** [mathworks/matlab-proxy#28]
### Summary

![屏幕截图 2023-12-07 093322](https://github.com/mathworks/matlab-proxy/assets/119525622/da777ce1-5c27-41f2-ba36-7420405f5a55)

The problem occured when I open the matlab2023b installed in a docker container through the browser.

**Comment by prabhakk-mw** [comment]
Hi @dutLQG 

Thank you for reporting this issue!

1. Is this issue consistently reproducible at your end? Have you tried starting the container again?
2. Are you seeing the same issue when you start MATLAB in terminal mode using:
`docker run -it --rm mathworks/matlab:r2023b`
and enter you online licensing information?

**Comment by dutLQG** [comment]
Thank you for reply!
1. I tried this in 3 devices, windows11, ubantu20.04, and macmini m1. The license only works in macmini. I have tried starting the container again.
2. The same issue is occurred in terminal mode.

**Comment by prabhakk-mw** [comment]
Hi @dutLQG 

This is a sporadic issue related to Online Licensing workflows present in MATLAB R2023b, and should be fixed in the next update that will be available to MATLAB R2023b towards the end of January.

I will circle back here when the update is available for Download.

Thank you!

**Comment by prabhakk-mw** [comment]
Hi @dutLQG 

This issue has been fixed in `MATLAB R2023b Update 6`.
Could you please install this update and try again?

Kindly let us know if the issue persists after moving to `MATLAB R2023b Update 6`, and I will reopen the issue to continue investigation.

Thank you !
