### ISSUE TITLE
Failed to authenticate by Online License Manager under http proxy environment

### ISSUE THREAD

**Issue by utotch** [mathworks/matlab-proxy#31]
### Summary

As I reported [here](https://github.com/mathworks-ref-arch/matlab-integration-for-jupyter/issues/10), I failed to authenticate my license by Online License Manager under http proxy environment.

I believe I input my correct Email and password because the manager responded, "Invalid Email or Password" for the wrong password but answered that it doesn't proceed for the correct password, which looked like it recognized the password.

[My observation]
I'm afraid the implementation of the matlab-proxy with aiohttp doesn't process HTTP_PROXY info properly.

This document shows how to introduce proxy support by using aiohttp:
https://docs.aiohttp.org/en/stable/client_advanced.html

This says,
```
Contrary to the requests library, it won’t read environment variables by default. But you can do so by passing trust_env=True into aiohttp.ClientSession constructor.:

async with aiohttp.ClientSession(trust_env=True) as session:
    async with session.get("http://python.org") as resp:
        print(resp.status)
```

by default, aiohttp ignores PROXY related environment variables.

according from mw.py code (line102-):
```
    async with aiohttp.ClientSession() as client_session:
        async with client_session.post(
            f"{mwa_api_endpoint}/tokens",
            headers={
                "content-type": "application/x-www-form-urlencoded",
                "accept": "application/json",
                "X_MW_WS_callerId": "desktop-jupyter",
            },
            data=aiohttp.FormData(
                {
                    "tokenString": identity_token,
                    "tokenPolicyName": "R2",
                    "sourceId": source_id,
                }
            ),
```

Client session is initialized without passing any arguments.

I'm afraid this code should be:
```
async with aiohttp.ClientSession(trust_env=True) as client_session:
```
that changes aiohttp to read proxy related environment variables.

--
my environment:
ubuntu linux 20 or 22 with Docker

### Browser(s) used

Chrome

**Comment by prabhakk-mw** [comment]
Hi @utotch 

Thank you for pursuing this. 

Would it be possible for you to share the values of the environment variables:
* http_proxy
* https_proxy
* HTTP_PROXY
* HTTPS_PROXY
* no_proxy
* NO_PROXY

Also, could you re-try by ensuring that : 
* `.mathworks.com` (notice the `.` before mathworks.com, which is meant to indicate all subdomains of mathworks.com)
* `localhost`

are present in the `no_proxy` & `NO_PROXY` values ?

Thanks

**Comment by utotch** [comment]
Hi, @prabhakk-mw

Thanks for the reply.
I just tried with setting the above no_proxy values, but nothing improved.

In my observation, we can't solve this problem just by changing proxy-related environment variables.

I show my setting partly (sorry for hiding some part for  privacy and security reason):
I tried below:
```
docker run -it --rm \
  --shm-size=512M \
  -p 8897:8888 \
  -e http_proxy=http://10.81.XXX.XX:8080 \
  -e HTTP_PROXY=http://10.81.XXX.XX4:8080 \
  -e https_proxy=http://10.81.XXX.XX:8080 \
  -e HTTPS_PROXY=http://10.81.XXX.XX:8080 \
  -e no_proxy=".mathworks.com,localhost,127.0.0.1" \
  -e NO_PROXY=".mathworks.com,localhost,127.0.0.1" \
  mathworks/matlab:r2023b -browser
```

And I believe the environment values are properly set.

```
$ env | grep -i proxy
no_proxy=.mathworks.com,localhost,127.0.0.1
https_proxy=http://10.81.XXX.XX:8080
NO_PROXY=.mathworks.com,localhost,127.0.0.1
HTTPS_PROXY=http://10.81.XXX.XX:8080
HTTP_PROXY=http://10.81.XXX.XX:8080
http_proxy=http://10.81.XXX.XX:8080
```

**Comment by prabhakk-mw** [comment]
Thank you @utotch 

I've been trying to recreate an environment in which I could test and then possibly fix this issue.

Do you happen to have a way for me to simulate a test environment that represents your setup?
If not, perhaps you could share how your environment is configured.
For example:

- Are you running containers on an --internal bridge network? 
- Where and who owns your proxy server, is it on a container as well? 
- What is the PROXY service you are using? `squid` or `nginx`  etc..
- Are you able to share its configuration file?

I'll try sharing a docker-compose file which showcases the configuration that I am testing under as well.

Thanks!

**Comment by utotch** [comment]
Hi, @prabhakk-mw
I checked the latest version, and it successfully worked!!

I appreciate you fixing this issue a lot!!

I suffered from this issue for a long time, preventing me from utilizing matlab-docker.
This solution helps a lot with my work.

Have a great day!
