### ISSUE TITLE
The Kernel Got disconnected mid work and never came back to work again

### ISSUE THREAD

**Issue by JayxTG** [mathworks/matlab-proxy#34]
### Summary

The kernal was disconnected automatically and never came back to life

### Browser(s) used

Microsoft Edge

**Comment by krisctl** [comment]
Dear @JayxTG,

Thanks for trying out jupyter-matlab-proxy! To help us diagnose the reason for Kernel disconnection, can you please provide some more information about your setup, environment, troubleshooting script output, etc? Also, please enable the debug logs by following the instructions mentioned [here](https://github.com/mathworks/jupyter-matlab-proxy/blob/main/troubleshooting/troubleshooting.md#enable-logging) and supply those logs as well.

For future Kernel-related issues, please consider using https://github.com/mathworks/jupyter-matlab-proxy/issues/new which is the main repository for MATLAB Kernel functionalities.
