### ISSUE TITLE
Close MATLABProxyApp automatically after Matlab has been stopped via browser

### ISSUE THREAD

**Issue by swdn133** [mathworks/matlab-proxy#36]
### Details of the feature

Usecase is the following: I have a docker container running matlab and matlab-proxy as described. I access matlab via browser and everything works fine. After I am finished working, I select the "Stop Matlab" option in the browser and matlab stops. 

My issue: the MATLABProxyApp process is still running. So my container is kept alive and continues blocking resources.

It would be great to have some kind of Timeout that autmatically stops the proxy app when no matlab is running.

I know that the env variable MWI_SHUTDOWN_ON_IDLE_TIMEOUT exists. But this is not the behaviour i would like to see. When setting this variable, the container will also be shutdown when matlab is still active but idle. 
I think it would be great to have the option to let matlab be alive when idle but shutdown the proxy-app when no matlab is running at all.

**Comment by prabhakk-mw** [comment]
Thank you @swdn133 !

Would a button along side the "Stop MATLAB" option that terminates both MATLAB and the MATLAB-PROXY-APP processes serve your needs?

**Comment by swdn133** [comment]
Hi @prabhakk-mw 

Yes, that would be a perfect option for my use case :)

**Comment by swdn133** [comment]
Awesome, thanks a lot!

**Comment by prabhakk-mw** [comment]
@swdn133 

A "Shut Down" button has been added to  `v0.23.1` of matlab-proxy

![image](https://github.com/user-attachments/assets/9c2211fd-a94e-45af-a749-8945eddec920)

Could you please confirm that updating to this version shows the button, and that it behaves as expected in your environment?

Thank you!

**Comment by swdn133** [comment]
That looks amazing. Thx for your work. I will check it out an come back to you asap.

**Comment by prabhakk-mw** [comment]
Thank you @swdn133 ! Please do let us know if this feature worked as expected on your end.

**Comment by prabhakk-mw** [comment]
Hi @swdn133 

Some of us were discussing this issue, and were hoping to get some more information related to this statement:

`My issue: the MATLABProxyApp process is still running. So my container is kept alive and continues blocking resources.`

When you say **kept alive**, I assumed you had some infrastructure that automatically closes containers when there are no user processes running.

Could you tell us more about how to configure such an environment?

**Comment by swdn133** [comment]
Hi @prabhakk-mw,

first of all: I was able to try out the new release and can now confirm that your feature works as expected and helps a lot with my workflow. Again: thx for your work.

**Comment by prabhakk-mw** [comment]
This clears up everything! 
Thank you for the quick and detailed response.

The will be happy to hear that the feature works as expected.
