### ISSUE TITLE
MATLAB Proxy randomly asks for authentication on first connection

### ISSUE THREAD

**Issue by robinkar** [mathworks/matlab-proxy#37]
### Summary

Hello, we noticed a problem where matlab-proxy occasionally asks for authentication when first connecting to it, even though the authentication was successful (`matlab-proxy-session-...` cookie gets set).
I.e. the user is presented with this screen after visiting `/matlab?mwi-auth-token=...` with the correct auth token:
![Screenshot from 2024-09-17 13-04-11](https://github.com/user-attachments/assets/ae52f01b-ee3a-47aa-948b-8491b1654c3c)

Clicking the submit button or refreshing the page does allow the user to continue to MATLAB successfully.

I spent some time tracing the problem and it seems that the frontend does not behave correctly when the `/authenticate` request finishes before the `/get_env_config` request.
Thus, adding `await asyncio.sleep(0.5)` to the [`get_env_config` request handler](https://github.com/mathworks/matlab-proxy/blob/6d3ad45bc5e38e44b748bd3833cd74d2b66fc2fe/matlab_proxy/app.py#L188) allows reproducing it consistently if cookies are cleared between attempts.
![Screenshot from 2024-09-17 13-06-48](https://github.com/user-attachments/assets/b74765ea-c189-4759-9328-217de6db40a7)

This was tested with matlab-proxy versions 0.18.1 and 0.21.0 with Firefox 128.2.0esr and Chromium 128.0.6613.119.
We are using matlab-proxy though [Open OnDemand](https://openondemand.org).

### Browser(s) used

Chrome, Firefox

**Comment by prabhakk-mw** [comment]
Hi @robinkar 

Thank you for the detailed report and for investing time in narrowing this down!

We will investigate and report back.

**Comment by prabhakk-mw** [comment]
@robinkar could you please confirm that v0.22.0 of the matlab proxy fixes this issue in your environment as well? 

Thanks!

**Comment by robinkar** [comment]
> @robinkar could you please confirm that v0.22.0 of the matlab proxy fixes this issue in your environment as well?
> 
> Thanks!

v0.22.0 does seem to fix the issue. Thanks for the quick fix!
