### ISSUE TITLE
__track_embedded_connector_state produces an infinite number of TIMEOUT error messages

### ISSUE THREAD

**Issue by tsuchm** [mathworks/matlab-proxy#38]
### Summary

In our JupyterHub server, `__track_embedded_connector_state` defined in https://github.com/mathworks/matlab-proxy/blob/89862aa588f804cc94b93159478279e5d4d6f894/matlab_proxy/app_state.py#L1154 produced the following error messages and caused disk full trouble.

```
Oct 10 10:50:25 jupyterhub bash[1983168]: ERROR:MATLABProxyApp::track_embedded_connector_state:: MATLAB did not start in 600 seconds!
Oct 10 10:50:25 jupyterhub bash[1983168]: ERROR:MATLABProxyApp::track_embedded_connector_state:: MATLAB did not start in 600 seconds!
Oct 10 10:50:25 jupyterhub bash[1983168]: ERROR:MATLABProxyApp::track_embedded_connector_state:: MATLAB did not start in 600 seconds!
(Snip)
(The same message was repeated 54556812 times)
```

We checked `__track_embedded_connector_state` and found the above error message is generated by 
https://github.com/mathworks/matlab-proxy/blob/89862aa588f804cc94b93159478279e5d4d6f894/matlab_proxy/app_state.py#L1206

And more, we found that the comment says

```
# Embedded connector is down, so check for how long it has been down and error out if necessary
# embedded_connector_start_time variable is updated by get_matlab_state().
```

However, we cannot find the code to update `embedded_connector_start_time` in https://github.com/mathworks/matlab-proxy/blob/89862aa588f804cc94b93159478279e5d4d6f894/matlab_proxy/app_state.py#L518

Thus, we think something regression was occured when implementing `get_matlab_state`.

Could you fix this trouble?

**Comment by Shushant2502** [comment]
Hi @tsuchm,

Thank you for investing time in narrowing this issue.

We are currently investigating what caused this regression and will report back once we have a fix.
