### ISSUE TITLE
Doc: explain how to release the license

### ISSUE THREAD

**Issue by MaximeWeyl** [mathworks/matlab-proxy#6]
When building my docker image with matlab-proxy, I need to rebuild and rerun the image several times.
I use my license through the online license server.
I often am unable to rerun the newly built image because the license was not released on the previous one I juste stopped (error License Manager Error -4)

I tried to use "Stop Matlab session", and "Sign out" buttons from the floating popup but the issue is still happening, and I have to wait for a long timeout for the license to be released and available again.

**Comment by diningPhilosopher64** [comment]
Hi @MaximeWeyl ,

Thank you for trying out the `matlab-proxy` package. Can you try typing out 'exit' in MATLAB and see if the licensing issue still persists ?

As the "Stop MATLAB Session" and the "Sign Out" buttons should also serve the same purpose, once after you know that you are able to license MATLAB, can you try again by clicking the "Sign Out" button and let us know if you are still seeing the "License Manager Error -4" error ?
